
server:
  port: 7777
  max-http-header-size: 4048576
spring:
  redis:
    password: ztgeoredis
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  application:
    name: ace-jszw
  main:
    allow-bean-definition-overriding: true
  thymeleaf:
    enabled: true
    encoding: UTF-8
    mode: HTML5
    prefix: classpath:templates/
    suffix: .html
  datasource:
    druid:
      stat-view-servlet:
        login-username: test
        login-password: test

    dynamic:
      druid:
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x' from dual
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
      datasource:
        admin:
          url: jdbc:mysql://localhost:3306/ag-admin-suqian?useUnicode=true&characterEncoding=UTF8&useSSL=true
          username: consignee
          password: ztgeo
          driver-class-name: com.mysql.jdbc.Driver
          druid: #这里可以重写默认值
            initial-size: 6
#        auth:
#          url: jdbc:mysql://172.18.0.147:3306/ag-auth?useUnicode=true&characterEncoding=UTF8&useSSL=true
#          username: consignee
#          password: ztgeo
#          driver-class-name: com.mysql.jdbc.Driver
#          druid:
#            initial-size: 6
      primary: admin
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null

jwt:  #jwt生成相关秘钥
  token-header: Authorization
  expire: 3600
  rsa-secret: xx1WET12^%3^(WE45
  user-service: ace-admin

url:
  ignore: /jwt/**,/webjars/**,/swagger-ui.html,/swagger-resources/**,/api/customDict/**,/api/test/**,/cache/**,/cache.**,/activity/**,/activity/modeler.html,/service/model/**,/service/editor/**,/api/sysManager/**,/api/biz/**  # 暂时将swagger解开限制

auth:
  serviceId: ace-auth
  user:
    token-header: Authorization
    limit-expire: 1440 # 一天过去,单位分钟

redis:
  aec-key: xx288&^^%$!@#4dc  #用于redis key的加解密操作 防止共秘钥被破解
  aec-iv: 0123456789abcdef
  pool:
    maxActive: 300
    maxIdle: 100
    maxWait: 1000
  host: 127.0.0.1
  port: 6379
#  password: ztgeoredis
  timeout: 2000
  sysName: ace-pubserver
  enable: true
  database: 0
# 配置数据库
mybatis:
  mapper-locations: "classpath*:mapper/*.xml"
  configuration:
    map-underscore-to-camel-case: true
# 配置swagger
swagger:
  enabled: true
  base-package: com.ztgeo.general
  title: wh-ztgeo-rec-project
  version: 1.0.0.SNAPSHOT
  description: 中天基础框架
  contact:
    name: wei

#jasypt:
#  encryptor:
#    password: BdaObXaELAA
immovable:
  type: 房地
glHouseSeller:
  obligeeType: 售房者
glHouseBuyer:
  obligeeType: 购房者
  obligeeDyqr: 抵押权人
  obligeeDyr: 抵押人
  obligeeQlr: 权利人
  obligeeYwr: 义务人
  obligeeZwr: 债务人
httpclient:
  seam: 23335       #杨智昊程序端口
  ip: 192.168.30.16
  #10.3.2.147    #登记平台ip
  windowAcceptanceIp: localhost   #一窗受理ip
  windowAcceptanceSeam: 7780      #一窗受理接口
businessType:
  clfFmortgage: MORTGAGE_OLD_TRAILER       #存量房预告抵押登记，（组合业务，预告+预告抵押））
  xjfFmortgage: MORTGAGE_NEW_TRAILER       #新建商品房预告抵押登记（组合业务，预告+预告抵押）
  grMortgageRegistration: MORTGAGE_PERSONAL #抵押登记(个人)
  grMortgageCancellation: DYZX  #（抵押注销(个人)）
  cancellationOfWarrants: QZZX  #（权证注销(个人)）
  registrationOfTransfer: ZYDJ  #（转移登记）
  registrationOfReplacement: HZDJ  #（换证登记）
  registrationOfSupplementary: BZDJ #（补证登记）
  forewarningMortgage: YGDY     #（预告抵押）
  transferAndMortgage: ZY_DY         #（转移及抵押，（组合业务，转移+抵押））；
  vormerkung: YGDJ         #预告登记
  areaNo: 320301
  dealPerson: zhangshoudong              #ADMIN
  bankPerson: yichuanyinhang

logging:
  level:
    com.springboot: debug

service:
  bdcbljgtjfw: ImmovableHandleResultService  #不动产办理结果提交服务
  bdcdbjghqfw: ImmovableBookingResultService #不动产登簿结果获取服务
  dydzzmzxfw: MortgageElectronicCertCancellation #抵押电子证明注销服务

# 跨服务数据合并 用于允许 字段的获取方式
merge:
  enabled: true
  guavaCacheNumMaxSize: 1000
  guavaCacheRefreshWriteTime: 10 # min
  guavaCacheRefreshThreadPoolSize: 10
  aop:
    enabled: true

mapper:
  mappers: com.github.wxiaoqi.security.common.mapper.CommonMapper

machine:
  ip: localhost
  post: 7777

chenbin:
  waitSec: 2
  maxConnCount: 20
  idType: 身份证,1$统一社会信用代码,8$组织机构代码,6
  registrationBureau:           #登记局
    username: tsdjj             #用户名
    password: 123456            #密码
    forecast:                   #预告预抵
      commercialHouse:          #商品房
        bizType: MORTGAGE_NEW_TRAILER
        pid: Proc-191105102109-R1X605S7
        #Proc-171013210700-3785RA40
        # Proc-180517142329-18NT00D7 宿迁的
        isSubmit: false
    secRec:                   #二手房
      transfer:               #转移
        wholeMoney:           #全款
          pid: P-ershoufang
          mid: 977759
  otherBureau:
    ga:                         #公安
      basicInfoUrl: http://10.13.0.240:9999/x
      basicInfoCheckUrl: http://10.13.0.240:9999/x
    mz:                         #民政
      url: http://10.13.0.240:9999/y
    gs:                         #工商
      url: http://10.13.0.240:9999/z
penghao:
    transferholdmap: true
    highestAuthority:      #去一窗受理拉取银行收件人员信息
        username: admin
        password: admin
    realEstateRenewal:
        pid: Proc-200323193911-4RWU8617                    #换证登记pid
    supplementaryEvidence:
        pid: Proc-200323194205-49156OSX                    #补证登记pid
    cancellationOfWarrants:
        pid: Proc-200323194438-7844U064                    #权证注销pid
    analysisProduction:
        pid: Proc-200323194648-484J72YW                    #转移析产pid
    inheritanceOrBequest:
        pid: Proc-180403153139-46641AJ0                    #继承或受遗赠pid
    rulingIndividual:
        pid: Proc-200323194648-484J72YW                    #法院裁定个人
    mortgageCancellation:       #抵押注销登记
        pid: Proc-180517124140-3MN26M71
          #Proc-180517124140-3MN26M71
    mortgageRegistration:       #抵押登记pid
        pid: Proc-191029093403-907K7232  #徐州
         # Proc-180517124205-2WM2423B 宿迁
    transferRegister:           #二手房转移登记
        pid: Proc-180403153139-46641AJ0
          #Proc-180403153139-46641AJ0
    transferMortgage:           #转移及抵押二手房
        pid: Proc-191127095613-2883V919
    contractinformation:        #合同消息获取
        ip: 172.18.0.112
        port: 8088
        region: BDC_jiawang
sq:
  bdcdydj: 340100
  ygdy: 327501
  dyzxdj: 342501
  bank:
    jt:          #交通
      username: sqjtgly     #用户名
      password: 123456     #密码
      resultPdf: 1    #是否登簿传输pdf
      itemName: 电子证明
      ip: 172.22.148.129
      post: 8001
      notice_url: JSRCIS/sq/sqResultNotice.do   #通知宿迁交通银行地址
      ftpIdentical: true    #银行上传共享平台与一窗受理是否在同一ftp

  jyht:     #商品房权利人信息
    api_id: 3Rkt5FPx    #二手房
    from_user: 0b6c220cdfc54288b6630eb1a7fa612f
    post: 8001
    ip: 10.13.0.240
    spf:           #商品房
      api_id: 3Rkt5FPx
      from_user: 0b6c220cdfc54288b6630eb1a7fa612f
      post: 8001
      ip: 10.13.0.240


  qsxx:
    api_id: JwWtYcW7
    from_user: 0b6c220cdfc54288b6630eb1a7fa612f
    serviceMethod: queryNsrWsqk
    swjgdm: 23213000000
    swrydm: 13213730007

djj:
  bsryname: sqbdc
  bsrypassword: 123456
  tsryname: tsdjj
  tsrypaaword: 123456

bank:
  bsryname: sqjtgly
  bsrypassword: 123456

tax:
  bsryname: testsw
  bsrypassword: 123456

tra:
  bsryname: testfg
  bsrypassword: 123456

gxjhpt:
  url: http://172.22.226.85:8001/

ycsl:
  url: http://localhost:7780/

bdc:
  old:
    url: http://192.168.30.16:12201/
  cx: #查询
    url: http://172.22.226.12:8099/
  jh: #交互
    url: http://172.22.220.10:8099/

other:
  url: http://localhost:7780/
  #url: http://172.22.226.85:8001/


PublicInspect:
  BDCZHURL: http://192.168.0.120:23335/api/services/app/BdcQuery/GetBdcInfoByBDCZH?BDCZH=%s
  DYZMHURL: http://192.168.0.120:23335/api/services/app/BdcQuery/GetBdcInfoByDYZMH?DYZMH=%s
  YGZMHURL: http://192.168.0.120:23335/api/services/app/BdcQuery/GetBdcInfoByYGZMH?YGZMH=%s


ETicket:
  Url: http://127.0.0.1:7777/ETicket/morkData
  LocalPath: E:/ETicket/

Feign:
  Tax: api/test/testTax
  #dataShareAction.do
  Tra: api/test/testTra
  #sqservice/bdc/getOneAcceptInfo
  ETicket: ETicket/morkData
  #getDzspAction.do
  Electric: api/test/testElec
  #share/electric/electric_lmgh_apply_api.action
  bdc:
    newPlat:
      query:
        djzlcx: out/sqapi/djzl     #登记资料查询
        cqzscx: out/sqapi/cqzs     #产权证书查询
        dyzmcx: out/sqapi/dycx     #抵押证明查询
        dzzzcx: out/sqapi/dzzzcx   #电子证照查询
        shsjcx: out/sqapi/shsj   #审核数据查询
        dbsjcx: out/sqapi/bdcdb   #登簿数据查询
      interact:
        wsjgjc: net/net/getAutoProcessStatus   #网申结果检查
        wsbjcj: net/net/AutoCreate   #网申办件创建
newplat:
  settings:                              #转内网保险机制，配置默认执行配置（当转内网时下述项未传入时使用）
  - key: esfzy                                #二手房转移
    sid: 167090000120
    sname: 存量房转移
    jsrid: Qo92Bsh5d2mOtWBzgDu
    jsrmc: 严帅
  - key: esfzydy                              #二手房转移及抵押
    sid: 167090000120,167090000092
    sname: 存量房转移,不动产抵押
    jsrid: Qo92Bsh5d2mOtWBzgDu
    jsrmc: 严帅
  - key: bdcdy                              #不动产抵押
    sid: 167090000092
    sname: 不动产抵押
    jsrid: Qo92Bsh5d2mOtWBzgDu
    jsrmc: 严帅
  - key: ygyd                               #预告预抵
    sid: 167090000108,167090000110
    sname: 新建商品房预告登记,新建商品房预告抵押
    jsrid: Qo92Bsh5d2mOtWBzgDu
    jsrmc: 严帅
  - key: dyzx                                #抵押注销登记
    sid: 167090000101
    sname: 不动产抵押注销
    jsrid: Qo92Bsh5d2mOtWBzgDu
    jsrmc: 严帅

ftp:
  ycSaveSetting: 1        #一窗使用本地或Ftp存储附件（1-FTP/0-本地）
  ifLocalBasePath: D:\ycsl\process\file\    #如果本地存储使用的基础路径，供本地存储模式下，外部向一窗受理发送附件使用
  isDealFtp:
    bdc: true #true
    jhpt: false
  settings:
  - key: ycsl
    ftpAddress: 127.0.0.1    #一窗受理ftp
    ftpPort: 21
    ftpUsername: test
    ftpPassword: test
    ftpTransMode: passive   #主被动模式，passive-被动/active-主动
    env: Win                #FTP环境，Win-Windows/Unix-Unix
  - key: bdc
    ftpAddress: 192.168.30.18    #不动产登记平台
    ftpPort: 21
    ftpUsername: ftpsvr
    ftpPassword: 123qwe!@#
    ftpTransMode: passive   #主被动模式，passive-被动/active-主动
    env: Win                #FTP环境，Win-Windows/Unix-Unix
  - key: jhpt
    ftpAddress: 127.0.0.1   #共享交换平台
    ftpPort: 21
    ftpUsername: test
    ftpPassword: test
    ftpTransMode: passive   #主被动模式，passive-被动/active-主动
    env: Win                #FTP环境，Win-Windows/Unix-Unix
dzzz:
  ignores:
    - 抵押注销
    - 权属注销
    - 查封
    - 查封注销
    - 异议
    - 异议注销
    - 预告注销
    - 预告
notice:
  settings:
  - key: bdc  #不动产
    userName: sqbdc
    password: 123456
    bdcSettings:
      settings:
      - key: acceptNotice
        noticeType: BDCAcceptNotice #不动产受理通知
        noticeText: 不动产受理回推通知，通知一窗系统，不动产受理已通过，驱动一窗对应的受理步骤自动提交
      - key: verifyNotice
        noticeType: BDCVerifyNotice #不动产审核通知
        noticeText: 不动产审核回推通知，通知一窗系统，不动产审核已通过，驱动一窗对应的审核步骤自动提交
      - key: resultNotice
        noticeType: BDCResultNotice #不动产登簿通知
        noticeText: 不动产登簿回推通知，通知一窗系统，不动产已成功登簿，驱动一窗对应的登簿步骤自动提交，同时回填登簿相关服务数据
      - key: discardNotice
        noticeType: BDCDiscardNotice #不动产作废通知
        noticeText: 不动产作废回推通知，通知一窗系统，不动产已作废办件，驱动一窗对应流程做出调整
  - key: zj   #住建
    userName: testfg
    password: 123456
    noticeSetting:
      noticeType: ZJExamineNotice #住建执行通知
      noticeText: 住建侧针对一窗系统推送的交易信息，进行网签交易合同，该通知则是通知一窗系统-网签合同的执行情况
  - key: sw   #税务
    userName: testsw
    password: 123456
    noticeSetting:
      noticeType: SWExamineNotice #税务执行通知
      noticeText: 税务侧针对一窗系统推送的不动产转移信息，进行税务核/完税操作，该通知则是通知一窗系统-税务核/完税的执行情况